// WARNING:  This file was autogenerated by java-spaghetti.  Any changes to this file may be lost!!!
package com.github.embassy_rs.rnfc.proxy.android.nfc;

@SuppressWarnings("rawtypes")
class NfcAdapter_ReaderCallback implements android.nfc.NfcAdapter.ReaderCallback {
    long ptr;

    private NfcAdapter_ReaderCallback(long ptr) {
        this.ptr = ptr;
    }

    @Override
    protected void finalize() throws Throwable {
        native_finalize(this.ptr);
    }
    private native void native_finalize(long ptr);

    @Override
    public void onTagDiscovered(android.nfc.Tag arg0) {
        native_onTagDiscovered(ptr, arg0);
    }
    private native void native_onTagDiscovered(long ptr, android.nfc.Tag arg0);

}
