[package]
name = "rnfc-acr122u"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
hex-literal = "0.4.1"
log = "0.4.20"
nusb = "0.1.3"
rnfc-traits = { path = "../rnfc-traits" }
