[package]
name = "rnfc-acr122u"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"

[dependencies]
hex-literal = "1.0.0"
log = "0.4.27"
nusb = "0.1.14"
rnfc-traits = { path = "../rnfc-traits" }
