[package]
name = "rnfc-android"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.3.1"
java-spaghetti = { git = "https://github.com/Dirbaio/java-spaghetti", rev = "d61bc3b8b969561a12a8f57d6e5b27fade99d973" }
log = "0.4.27"
rnfc-traits = { path = "../rnfc-traits" }
