
include = [
    "android/nfc/*",
    "android/app/Activity",
    "android/os/Bundle",
    "android/content/Context",
    "android/content/ContextWrapper",
    "android/view/ContextThemeWrapper",

    "java/lang/Object",
    "java/lang/Throwable",
    "java/lang/StackTraceElement",
    "java/lang/String",

    "java/util/Iterator",
]

include_proxy = [
    "android/nfc/NfcAdapter$ReaderCallback",
]

[[documentation.pattern]]
class_url_pattern           = "https://developer.android.com/reference/{CLASS}.html"
method_url_pattern          = "https://developer.android.com/reference/{CLASS}.html#{METHOD}({ARGUMENTS})"
constructor_url_pattern     = "https://developer.android.com/reference/{CLASS}.html#{CLASS.INNER}({ARGUMENTS})"
field_url_pattern           = "https://developer.android.com/reference/{CLASS}.html#{FIELD}"
argument_seperator          = ",%20"


[logging]
verbose = true

[input]
files = [
    "/home/dirbaio/Android/Sdk/platforms/android-33/android.jar",
]

[output]
path = "src/bindings.rs"

[codegen]
method_naming_style             = "java"
method_naming_style_collision   = "java_short_signature"
keep_rejected_emits             = false
proxy_path_prefix = "com/github/embassy_rs/rnfc/proxy"

[codegen.field_naming_style]
const_finals    = true
rustify_names   = false
getter_pattern  = "{NAME}"
setter_pattern  = "set_{NAME}"
