[package]
name = "rnfc-traits"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"

[dependencies]
defmt = { version = "1", optional = true }
log = { version = "0.4.27", optional = true }
