[package]
name = "rnfc-traits"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
defmt = { version = "0.3", optional = true }
log = { version = "0.4.14", optional = true }
